name: Style checker

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/lint.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.py"
      - ".github/workflows/lint.yml"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest colorama

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./src/ninjar --count --select=E9,F63,F7,F82 --show-source --statistics

          # exit-zero treats all errors as warnings.
          flake8 ./src/ninjar --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
