name: SSH
on: [workflow_dispatch]

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: "3.11"

      - name: Install build-script dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          pip install mypy colorama flake8 pytest

      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3
